### ISSUE TITLE
collect.php running error

### ISSUE THREAD

**Issue by samuelpetrosyan** [glu000/bbb-usage#2]
When I run `/usr/bin/php /var/www/html/bbb-usage/collect.php` I face this error:

`PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/bbb-usage/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:490`

Please describe how to solve it!

**Comment by Lutice** [comment]
hello
you need to install php-xml on your server where you use the collect.php

**Comment by samuelpetrosyan** [comment]
Thanks. It helped.
But now it gives me another Error:
`PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /var/www/html/bbb-usage/bbb-usage/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:490`

What should I implement?

**Comment by glu000** [comment]
Could you try to open index.php and check if the current data is shown correctly

**Comment by samuelpetrosyan** [comment]
@glu000 What data I should check in index.php?

**Comment by glu000** [comment]
Just open index.php in the browser and check, of the current data is shown correctly like in the attached screenshot
 
![Bildschirmfoto 2020-05-25 um 11 24 26](https://user-images.githubusercontent.com/25256186/82799521-74bd8e80-9e7a-11ea-90a6-a2ac6b3d6105.jpg)
