### ISSUE TITLE
NOT ISSUE: Get additional information of meeting

### ISSUE THREAD

**Issue by samuelpetrosyan** [glu000/bbb-usage#5]
Dear developers,
Thank you so much for this useful tool. 

It would be useful if I could get also additional information of meeting. Some information is available via **getMeetings** API call.
How can I get e.g **meetingName**, **createDate**, **attendees** or another info, which are visible from getMeetings API call.

Thanks in advance!

**Comment by glu000** [comment]
Hi samuelpetrosyan,

thanks for your feedback! The purpose of this tool is to generate anonymous usage statistics. Collecting data like meeting name and names of attendees would be a violation of GDPR. Therefore it's not planned to implement this feature

Regards
Guenter
